### ISSUE TITLE
Feature Request: Two Finger Pinch

### ISSUE THREAD

**Issue by alextorma** [witty91/gester#1]
Hey there, I noticed you said you weren't going to be adding any more features, but you were open to suggestions. Might I suggest a two finger pinch in/out? 

It's been achieved on this fork, but I don't know what that person's doing as adding commands to the config.h doesn't actually seem to do anything and there's no place to submit an issue there. Since this one works out of the box after some very minimal configuration, I was wondering if that was a feature that could be added?
If not, no problem, and thank you for getting the ball rolling on gester!

**Comment by alextorma** [comment]
I've worked on updating the code for the zgester fork. Closing this!

**Comment by witty91** [comment]
Hi there, I apparently don't get notifications on issues by default. I think two finger pinch gestures should be very much possible. The rule to identify them would basically looking at the two vectors and seeing if their direction was exactly opposite (withing a margin of error, obviously). So, one would need to normalize the vectors and see if vec1=-vec2... I may add that in in the near future, since I have been thinking about adding some more swipes on the screen edges anywas :-)
