### ISSUE TITLE
Not actually an issue, just couldn't figure out how to msg you

### ISSUE THREAD

**Issue by Jeppe03** [witty91/gester#4]
Hi, 
Sorry I'm posting this as an issue, but I couldn't figure out how to get in contact with you in any other way.

Even though I'm pretty experienced with computers etc. I just moved from Windows to Linux and I could really use this gester tool (used a pretty similar program on windows and it would be nice to be able to do the same things now too).
But I do not know how I would even go by installing and using this, therefore I was wondering if you could give me a brief explanation of how I could install it.
Thanks in advance! (even if you won't help me you made a great tool that will help me a ton in the future)

**Comment by witty91** [comment]
Hi there,
not a big deal...I guess a bit more of an installation instruction wouldn't hurt anyway. Could you let me know which distro and possibly which device you are using it on? That would make it easier to give more specific feedback.

**Comment by Jeppe03** [comment]
Sweet! I run arch Linux on an HP spectre x360 13.

**Comment by witty91** [comment]
Okay, so first the downloading:
If you have installed git, you can just run
`git clone https://github.com/witty91/gester.git` on a terminal.
Otherwise you could also download it as a zip, I believe.
Then you will have to find out some things about your system and write the appropriate information into the config.h file. I did put some information of what is needed in there as comments. The most important one, to get this working in normal orientation is the device name of the touch input. In my case this is:
` /*path to the input event, need to be part of input group in order to read*/
        char devname[] = "/dev/input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-event-if00";`
because I have a wacom tablet in there. I looked at the archwiki, but I am not entirely sure what kind of touch input device the spectre uses. Have a look in the `/dev/input/by-id/` path, you will probably find it in there.
I think the accelerometer stuff is easier to be ignored for now. You can deal with that, when everything else is running.
`int xmax = 11747; int ymax = 6607;`
Are the maximum values the touchscreen outputs as positions. These are like x- and y-coordinates on the screen. x is running from the left to the right. I used "evtest" (from the arch community repos) to find these values by running it on the input event thingy. This may also help you in identifying the correct input event. The next couple values are something to play around with. By default I have set the angle to change in steps of 5 in order to increment volume and screen brightness in these steps for example.
And then what is left, is the array, where you can put any commands you want to run. I have left mine in there so that they may be useful as reference. For the rotations the commands get the rotational value appended so that it can be used in the command.
I hope this helps for now, good luck :-)

**Comment by Jeppe03** [comment]
Thank you soo much!
I've found the path to my input device, and I think I've found the right x and y values, but either I'm dumb and just didn't understand how to launch the program correctly or something else is wrong... I'm sorry to bother you more but would you mind explaining how I'd launch the program? XD (sry for being so stupid)

**Comment by witty91** [comment]
Alright, so when you have put that information into config.h, then you can run `make` to create the binary. It should appear in bin/Release If I remember correctly. You can manually start it from the command line with ./gester there. Or you can run `sudo make install` to put the binary into /usr/local/bin/ , which should make you able to just call "gester". You can then also configure IT to autostart in a number of ways, depending on your desktop environment or window manager. In my case I have a line in my ~/.xprofile that simply says 
`gester &`
If you want to change the config afterwards just change the config.h and run the make commands again.

**Comment by Jeppe03** [comment]
Yeah, then the problem is something else... the gestures don't get recognized and my touch inputs just act as mouse input. Problem is that both screens get that same input so if I do a pinch gesture with a browser open on my second monitor, it zooms in, in the browser XD 
I'll have to look into this a bit further, ill get back in touch if I need to ask about something else that's directly connected to your program.
Thanks again!

**Comment by witty91** [comment]
When you run it from the command line manually, you should get the recognized gestures and some other output...as long as that works, putting in any scripts should be fine.
I haven't tried what happens in multi-monitor setups at all, so I can't really give any advice there. And for pinch gestures: I have only started trying that out in the new branch, there aren't any commands connected to it yet, so I wouldn't expect that particular gesture to work. The stuff I use the most is 2- and 3-finger rotations for volume and brightness and the bottom swipe for an on-screen keyboard.
Edit: and stuff like zoom in certain programs is actually why I wouldn't use a pinch gesture myself...in my experience it's probably the most used gesture in programs and will therefore cause interference here :-/

**Comment by Jeppe03** [comment]
When I run it in the command line I get a lot of output saying the accelerometer isn't configured, but nothing happens when I try to use gestures. Since I had problems with dual monitor touch before I'll try and see if there is any configuration needed to be done there, but when I get that to work I'll try to get gestures to work.

If you are ok with it, would you mind getting in contact with me in some other way than through these comments? Would be nice to have someone to ask/talk to that's running (almost) the same setup, since I'm very new to all of this :)

**Comment by witty91** [comment]
You could comment out that line in the source code -- should be line 117 in main.cpp .
You can send me an email at git-stuff[at]ch-witt.de if you like. I will however be quite busy in the upcoming time, so replies may take a bit longer (like this one already did).

**Comment by witty91** [comment]
Hey,
you may still feel free to send me an e-mail if you like. 
Other than that I'll close the issue here.
Best wishes
